#!/usr/bin/env python

import os, glob

if __name__ == '__main__':

	for root, dirs, files in os.walk("."):
		for name in files:
			if name[0] == '.':
				abs_fp = os.path.join(root, name)
				new_fp = os.path.join(root, name[1:])
				os.rename(abs_fp, new_fp)
